name: Pull Request
on: 
  pull_request:
    branches:
      - master
jobs:
  check-notebook-changes:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2.3.1
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Add conda to path
        run: export PATH="$CONDA/bin:$PATH"
      
      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Check user permission
        id: permission
        uses: scherermichael-oss/action-has-permission@master
        with:
          required-permission: read
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get changed files
        if: steps.check.outputs.has-permission
        id: files
        uses: jitterbit/get-changed-files@v1

      - name: Check files for read-only accesses
        if: steps.check.outputs.has-permission
        run: python build/check_notebook_changes.py ${{ steps.files.outputs.all }}

  check-notebooks:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2.3.1
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Add conda to path
        run: export PATH="$CONDA/bin:$PATH"
      
      - name: Install Requirements
        run: pip install -r requirements.txt
      
      - name: Check notebooks
        env:
          IMAGE_MAX_SIZE: 1500000
        run: python build/check_notebooks.py

  build-notebook:
    needs: [check-notebooks, check-notebook-changes]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2.3.1
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Add conda to path
        run: export PATH="$CONDA/bin:$PATH"
      
      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2.3.1

      - name: Build notebooks
        run: python build/build_notebooks.py --baseurl /${{ github.event.repository.name }}

      - name: Jekyll Build
        uses: jerryjvl/jekyll-build-action@v1
